name: Run Scraping Script

on:
  workflow_dispatch:
  schedule:
    - cron: '00 6 * * *'
    - cron: '00 7 * * *'
    - cron: '00 8 * * *'
    - cron: '00 10 * * *'
    - cron: '00 11 * * *'
    - cron: '00 13 * * *'
    - cron: '00 14 * * *'
    - cron: '00 16 * * *'
    - cron: '0 18 * * *'
    - cron: '0 20 * * *'
    - cron: '0 22 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Python script
        run: python script.py
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}

      - name: Migrate Data to SQLite
        run: sql_data_migration.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add gpu_listings.csv
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'Update gpu_listings.csv and gpu_listings.db'
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
