name: Run Scraping Script

on:
  workflow_dispatch:
  schedule:
    - cron: '11 22 * * *'
    # Additional times as needed
    - cron: '0 6 * * *'   # 6:00 AM UTC
    - cron: '0 12 * * *'  # 12:00 PM UTC
    - cron: '0 18 * * *'  # 6:00 PM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Python script
        run: python script.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add gpu_listings.csv
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'Update gpu_listings.csv'
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}